### ISSUE TITLE
Espresso `static_job` doesn't work "as-is"

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [Quantum-Accelerators/quacc#1412]
### Details about the quacc environment

- **quacc version**: 0.4.6
- **Python version**: 3.9+

### What is the issue?

All quacc recipes should have an option that works "as-is" given the default settings. However, doing a default calculation with bulk Cu yields an error that no smearing is applied. A default preset should be selected, even if it is not perfect.

I would generally recommend Gaussian smearing with a sufficiently small `degauss`, which is safe for all kinds of systems.

### How can we easily reproduce the issue?

```python
from ase.build import bulk
from quacc.recipes.espresso.core import static_job

atoms = bulk("Cu")
static_job(atoms)
```

### Suggestions

Maybe we have a `BasicSet.yaml` that looks something like:

```yaml
system:
  ecutwfc: 60
  ecutrho: 240
  occupations: smearing
  degaus: 0.001

kspacing: ???

parent_pseudopotentials: sssp_1.3.0_pbe_efficiency.yaml
```

And then have each recipe have `preset: str | None = "BasicSet"`
