### ISSUE TITLE
Set up auto-merge for `dependabot[bot]` and `deepsource-autofix[bot]`

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [Quantum-Accelerators/quacc#1634]
### What would you like to report?

Below is what I tried adding to the test suite, but it doesn't have the permissions to do `gh pr merge --auto --merge "$PR_URL"`. I get back `GraphQL: Resource not accessible by integration (enablePullRequestAutoMerge)`. I also want to enable this for `deepsource-autofix[bot]`.

```yaml

  metamerge:
    name: 'meta-automerge'
    needs:
      - tests-core
      - tests-engines-covalent
      - tests-engines
      - tests-engines2
      - tests-psi4
      - tests-defects-phonons-espresso
      - tests-tblite-dftbplus
      - tests-qchem-sella
      - tests-mlps
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
